# confing/config.yaml
defaults:
  - override hydra/job_logging: disabled

# model hyperparameters
model:
  model_name: BasicLM
  n_layers: 16
  n_heads: 16
  n_embd: 768
  max_length: 512

# training settings
training:
  run_name: "basic_lm_experiment"
  batch_size: 42
  lr: 1e-3
  epochs: 100
  mixed_precision: false
  max_grad_norm: 1.0
  train_ratio: 0.8
  val_ratio: 0.2


# inference settings
inference:
  kv_cache: true
  quantized: false # Only use when CUDA is not available
  mixed_precision: false # Only use when CUDA is not available
  model_path: "../models/model_basic_lm_experiment.pth"
